log_path: "logs/application.log"
folders:
- folder_path: "/home/janek/niestudia"
  important_files:
    - "important1"
    - "important2"
  operations_to_watch:
    - "create"
    - "write"

- folder_path: "/home/janek/studia"
  important_files:
    - "important3"
    - "important4"
  operations_to_watch:
    - "remove"
    - "rename"
    - "create"
    - "write"

- folder_path: "/home/janek/test"
  important_files:
    - "test"
  operations_to_watch:
    - "create"

- folder_path: "/etc/test3435"
  important_files:
  operations_to_watch:
    - "create"
    - "write"
    - "remove"
